version: '3.8'
services:
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    restart: unless-stopped
    ports:
      - "8181:8181"
    volumes:
      - ./config:/config
    env_file:
      - .env
