version: '3.8'
services:
  listmonk:
    image: listmonk/listmonk:latest
    container_name: listmonk
    ports:
      - "9000:9000"
    environment:
      - TZ=Europe/Paris
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: postgres:13
    container_name: listmonk_db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: unless-stopped
