version: '3.8'
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    volumes:
      - ./config:/config
      - ./tvshows:/tv
      - ./movies:/movies
    restart: unless-stopped
    env_file:
      - .env
