version: "3"
services:
  database:
    image: postgres:11.6-alpine
    environment:
      - POSTGRES_USER=codimd
      - POSTGRES_PASSWORD=YourP@swword
      - POSTGRES_DB=codimd
    volumes:
      - "./database-data:/var/lib/postgresql/data"
    restart: always
  codimd:
    image: hackmdio/hackmd:2.4.1
    environment:
      - CMD_DB_URL=postgres://codimd:YourP@swword@database/codimd
      - CMD_USECDN=false
    depends_on:
      - database
    ports:
      - "3500:3000"
    volumes:
      - ./upload-data:/home/hackmd/app/public/uploads
    restart: always
volumes:
  database-data: {}
  upload-data: {}

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet:  172.16.3.0/24
