# ==============================================================================
# Fichier : fail2ban_envoy_jail.conf
# Description : Filtre Fail2ban pour les reverse proxys Envoy
# Environnement : Lab public de démonstration
# Path cible : /etc/fail2ban/jail.d/envoy.conf
# ==============================================================================

[envoy-ddos]
enabled  = true
port     = http,https
protocol = tcp
filter   = envoy-ddos
logpath  = /var/log/envoy/access.log
# Si une IP fait plus de 150 requêtes en 1 minute, on la bannit
findtime = 60
maxretry = 150
# Bannie pour 24h
bantime  = 86400
# Action de blocage classique via Iptables, et notification Telegram
action   = iptables-allports[name=envoy-ddos]
           telegram[name="Envoy DDoS", chat_id="<VOTRE_CHAT_ID>"]

[envoy-4xx]
enabled  = true
port     = http,https
filter   = envoy-4xx
logpath  = /var/log/envoy/access.log
# Bannir les scanners web (Ffuf, Dirb) qui génèrent trop d'erreurs 404/403
findtime = 60
maxretry = 20
bantime  = 3600
action   = iptables-allports[name=envoy-4xx]